---
title: "SIF Downscaling using OpenEO and the Copernicus Data Space Ecosystem (CDSE)"
format:
  html:
    toc: true
    toc-location: left
css: styles.css
jupyter: python3
toc: true
toc-depth: 5
toc-title: Contents
author: 
    - name: Daniel E. Pabon-Moreno
      email: dpabon@bgc-jena.mpg.de
      attributes:
        corresponding: true
      affiliations:
        - ref: bgc
    - name: Qiqi Deng
      affiliations:
        - ref: bgc
    - name: Gregory Duveiller
      affiliations:
        - ref: bgc

affiliations:
  - id: bgc
    name: Max-Planck Institute for Biogeochemistry
    city: Jena
    country: Germany


---
### Acknowledgement

This project has received funding from the [Open-Earth-Monitor Cyberinfrastructure](https://earthmonitor.org/) project that is part of European Union's Horizon Europe research and innovation programme under grant [101059548](https://cordis.europa.eu/project/id/101059548).

### Introduction

Sun-induced chlorophyll fluorescence (SIF) is a re-emitted signal directly originating from the photosynthetic system, representing plant fluorescence observed from space. It is therefore considered a direct measure of plant physiological status and responses to environmental changes, while also serving as a potential indicator for estimating global gross primary productivity (GPP). However, the revisit cycles and operational altitudes of existing SIF observation platforms limit their spatio-temporal resolution. This results in decoupling between the linear relationship between global-scale SIF and GPP at finer temporal and spatial scales.
The Sentinel-5P TROPOMI sensor, with its daily nadir spatial resolution of 3.5 × 5.5-7 km, enables more detailed observation of SIF/GPP in terrestrial ecosystems. The following example illustrates the downscaling process (i.e., increasing the spatial resolution) for SIF based on an mechanistic model that relates SIF with land-surface temperature, and NIRv (a vegetation index).

### Libraries
We will need the following libraries to run the downscaling processor
```{python}
import openeo
import rioxarray as rio

"""
Currently there is an issue with openEO back-end that doesnt allow us to upsample datacubes (For more details see [here](https://forum.dataspace.copernicus.eu/t/how-to-spatial-upsampling-when-using-resample-cube-spatial/4358/6)). For this reason we will need some other libraries to process the parameters cube locally, perform a spatial upsample, create a stac catalog and publish the file and catalog on github.
This is needed to create a STAC item for the upsampled parameters:
"""
import pystac
from pystac.extensions.projection import ProjectionExtension
from pystac.extensions.eo import EOExtension
from datetime import datetime
from shapely.geometry import box, mapping
import json
import subprocess

# For data visualization
import xarray as xr
import matplotlib.pyplot as plt

# For spatial resampling
import xesmf as xe
import xarray_regrid
import numpy as np
```

## Study number 1: Downscaling SIF in the Iberian peninsula

### Area of Interest and Time Period

Before going into the details of the datasets, we need to define an area of interest and time period for our analysis. For this example, we will focus on the Iberian Peninsula during the time period between 2023-07-17 and 2023-07-23.

```{python}
spatial_extent_prototype = {
    "west": -10.0,
    "east": 0.0,
    "south": 35.0,
    "north": 45.0,
}

temporal_extent_prototype = ["2023-07-17", "2023-07-21"]
```

```{python}
# | echo: false
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib.patches import Rectangle


def plot_world_with_bbox(bbox, title="World Map with Bounding Box"):
    """
    Plot world map with a bounding box overlay.

    Parameters:
    -----------
    bbox : tuple or list
        Bounding box coordinates as (min_lon, min_lat, max_lon, max_lat)
    title : str
        Plot title
    """
    min_lon, min_lat, max_lon, max_lat = (
        bbox["west"],
        bbox["south"],
        bbox["east"],
        bbox["north"],
    )

    # Create figure and axis with PlateCarree projection
    fig, ax = plt.subplots(
        figsize=(15, 10), subplot_kw={"projection": ccrs.PlateCarree()}
    )

    # Add map features
    ax.add_feature(cfeature.LAND, facecolor="lightgray", edgecolor="none")
    ax.add_feature(cfeature.OCEAN, facecolor="lightblue")
    ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
    ax.add_feature(cfeature.BORDERS, linewidth=0.3, linestyle=":")
    ax.add_feature(
        cfeature.LAKES, facecolor="lightblue", edgecolor="black", linewidth=0.3
    )

    # Add gridlines
    gl = ax.gridlines(
        draw_labels=True, linewidth=0.5, color="gray", alpha=0.5, linestyle="--"
    )
    gl.top_labels = False
    gl.right_labels = False

    # Set global extent
    ax.set_global()

    # Draw bounding box
    width = max_lon - min_lon
    height = max_lat - min_lat

    bbox_patch = Rectangle(
        (min_lon, min_lat),
        width,
        height,
        linewidth=2,
        edgecolor="red",
        facecolor="none",
        transform=ccrs.PlateCarree(),
        zorder=5,
    )
    ax.add_patch(bbox_patch)

    # Add a label for the bbox
    center_lon = (min_lon + max_lon) / 2
    center_lat = (min_lat + max_lat) / 2
    ax.text(
        center_lon,
        max_lat + 5,
        "Area of Interest",
        transform=ccrs.PlateCarree(),
        ha="center",
        fontsize=10,
        color="red",
        weight="bold",
    )

    ax.set_title(title, fontsize=14, weight="bold", pad=20)

    plt.tight_layout()
    return fig, ax


fig1, ax1 = plot_world_with_bbox(spatial_extent_prototype, " ")

plt.show()

```

### Connecting to CDSE using openEO

To connect to the openEO insfrastructure in the CDSE we need to create a connection:

::: {.callout-important}
If you're using Positron to run this tutorial please first open the ```authentication.ipynb``` notebook run the cells there, and follow the instructions. This step is only necessary once, the next time you run the cells of this tutorial openeo will use refresh authentication tokens.
:::

```{python}
connection = openeo.connect(
    "https://openeofed.dataspace.copernicus.eu/"
)

connection.authenticate_oidc()
```

This will open a tab in the web-browser where the user needs to authenticate using the CDSE credentials. For more details on openEO in CDSE please see: [https://dataspace.copernicus.eu/analyse/openeo](https://dataspace.copernicus.eu/analyse/openeo)

Then we can see the data collections that are available:

```{python}
# | eval: false

connection.list_collections()
```

:::{.scrolling}

```{python}
# | echo: false

connection.list_collections()
```

:::


### Variables

For this tutorial we will use the following datasets/variables:

Target:

| Variable name | Collection | Band Name | Spatial resolution|
|--|--|--|--|
|Sun-Induced Flourescence| [Dong Li SIF](https://raw.githubusercontent.com/dpabon/SIF_downscaling_CDSE/refs/heads/main/data/SIF_20180629.json)| ```SIF```| 5 km |

Currently there are two SIF gridded products derived from Sentinel-5p that are availables:

1. [S5P-PAL SIF](https://data-portal.s5p-pal.com/products/troposif.html). This product is generated by the Sentinel-5P Product Algorithm Laboratory (S5P-PAL) and contains modified Copernicus Sentinel data processed by S[&]T. Unfortunately, the current (at least at: 2025-12-01) STAC dissemination only include plain netcdf files and not cloud optimized data format. Currently the [Atmosphere Virtual Lab project](https://atmospherevirtuallab.org/) is working in provided zarr datacubes for the L3 products, including SIF.

2. [Dong LI SIF](https://www.sciencedirect.com/science/article/pii/S0034425725003918#da0005). This product uses an artificial neural network to retrieve SIF from Sentinel-5p observations. Thanks to Dong Li for provinding us with a [gridded example of the product](https://github.com/dpabon/SIF_downscaling_CDSE/blob/main/data/SIF_20180629.tif) and the [stac item](https://github.com/dpabon/SIF_downscaling_CDSE/blob/main/data/SIF_20180629.json) necessary to ingest the product in the openEO-CDSE infrastructure. This files can be found in the data directory of the [repository](https://github.com/dpabon/SIF_downscaling_CDSE).

Predictors:

| Variable name | Collection | Band Name | Spatial resolution |
|--|--|--|--|
|Land Surface Temperature| ```SENTINEL3_SLSTR_L2_LST```| ```LST```| 1 km|
|Near Infrared Vegetation Index| ```SENTINEL3_OLCI_L2_LAND```| ```RC681```, ```RC865```| 300 m|
: SIF predictors {#tbl-predictors}

#### Creating openEO datacubes for the variables

```{python}
# Testing SIF - Dong Li

cube_SIF_original_median = connection.load_stac(
    "https://raw.githubusercontent.com/dpabon/SIF_downscaling_CDSE/refs/heads/main/data/2023-07-SIF/5_days_composites/SIF_20230717_20230721.json",
    bands=["SIF"],
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
)

```


```{python}



cube_LST = connection.load_collection(
    "SENTINEL3_SLSTR_L2_LST",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["LST"],
)

cube_LST_qc = connection.load_collection(
    "SENTINEL3_SLSTR_L2_LST",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["confidence_in"],
)

red = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["RC681"],
)

nir = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["RC865"],
)

cube_NIRv = ((nir - red) / (nir + red)) * nir

cube_NIRv = cube_NIRv.rename_labels(dimension="bands", target=["NIRv"])

cube_OLCI_qc = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["LQSF"],
)

```




#### Masking clouds


```{python}

mask = cube_LST_qc > 5000

cube_LST_masked = cube_LST.mask(mask)

```

```{python}

mask_olci = cube_OLCI_qc > 10000

cube_NIRv_masked = cube_NIRv.mask(mask_olci)
```


If we call one of the cubes we can see the process graph that is created by openEO:
 
```{python}
cube_LST_masked
```

### Reducing the time dimension

For this analysis we will compute a composite of the area of interest using all the observations during the time period for all the variables except SIF that is already one time step observation.

```{python}

cube_LST_median = cube_LST_masked.reduce_temporal(reducer="max")

cube_NIRv_median = cube_NIRv_masked.reduce_temporal(reducer="median")

```

#### Resampling OLCI products at 1 km

Originally the OLCI products are 300 meters resolution, as Sentinel-3 LST product is at 1 km (@tbl-predictors) we need to resample the NIRv cube:

```{python}
cube_NIRv_median_1 = cube_NIRv_median.resample_cube_spatial(
    target=cube_LST_median, method="med"
)
```

```{python}
cube_LST_median
```

#### Resampling OLCI products at 1 km

Originally the OLCI products are 300 meters resolution, as Sentinel-3 LST product is at 1 km (@tbl-predictors) we need to resample the NIRv cube:

```{python}
cube_NIRv_median_1 = cube_NIRv_median.resample_cube_spatial(
    target=cube_LST_median, method="med"
)
```

### Inspecting the variables

Then we will inspect the products, for that we need to execute the processors for each cube, save it locally, open and plot.


```{python}
# cube_SIF_original_median.execute_batch(outputfile="data/cube_SIF_median_iberian_peninsula.tif")
# cube_LST_median.execute_batch(outputfile="data/cube_LST_median_iberian_peninsula.tif")
# cube_NIRv_median_1.execute_batch("data/cube_nirv_1km_mask_iberian_peninsula.tif")
```



```{python}
cube_sif_local = rio.open_rasterio(
    filename="data/cube_SIF_median_iberian_peninsula.tif", mask_and_scale=True
)
cube_lst_local = rio.open_rasterio(filename="data/cube_LST_median_iberian_peninsula.tif")
cube_nirv_local = rio.open_rasterio(filename="data/cube_nirv_1km_mask_iberian_peninsula.tif")

```

```{python}
fig, axs = plt.subplots(nrows=3, figsize=(5, 12))
cube_sif_local.plot(ax=axs[0], vmin=0)
axs[0].set_title("SIF")
cube_lst_local.plot(ax=axs[1])
axs[1].set_title("LST")
cube_nirv_local.plot(ax=axs[2])
axs[2].set_title("NIRv")

plt.tight_layout()

```



### Spatial resampling to match the SIF resolution product


```{python}
cube_LST_median_low = cube_LST_median.resample_cube_spatial(
    target=cube_SIF_original_median, method="med"
)

cube_NIRv_median_low = cube_NIRv_median.resample_cube_spatial(
    target=cube_SIF_original_median, method="med"
)

```


```{python}
cube_LST_median_low
```

Merging all the cubes at low resolution (SIF original resolution)

```{python}
dataset_SIF_low = cube_SIF_original_median.merge_cubes(cube_LST_median_low)

dataset_SIF_low = dataset_SIF_low.merge_cubes(cube_NIRv_median_low)

```



Adding two dummy variables to the datacube to match the number of oputput parameters of the optimization function.

```{python}
dataset_SIF_low = dataset_SIF_low.merge_cubes(
    other=cube_SIF_original_median.rename_labels(dimension="bands", target=["dummy_1"])
)
dataset_SIF_low = dataset_SIF_low.merge_cubes(
    other=cube_SIF_original_median.rename_labels(dimension="bands", target=["dummy_2"])
)
```



```{python}
# | eval: false
# dataset_SIF_low.execute_batch(outputfile="data/sif_predictors_cube_low_iberian_peninsula.nc")
```

Let's check the cube after resampling

```{python}
dataset_sif_low_local = xr.open_dataset("data/sif_predictors_cube_low_iberian_peninsula.nc")
print(dataset_sif_low_local)
```

```{python}
fig, axs = plt.subplots(nrows=3, figsize=(5, 12))
dataset_sif_low_local["SIF"].plot(ax=axs[0], vmin = 0)
axs[0].set_title("SIF")
dataset_sif_low_local["LST"].plot(ax=axs[1])
axs[1].set_title("LST")
dataset_sif_low_local["NIRv"].plot(ax=axs[2])
axs[2].set_title("NIRv")
plt.tight_layout()

```


### SIF parameter optimization at low spatial resolution

To predict SIF we use the following formulation:

::: {#def-sif}
$$SIF = f(V) \cdot f(T)$$
:::

where $f(V)$ represents the vegetation module and $V$ is a vegation index: 
$$f(V) = b_2 \cdot V^{b_1}$$


$f(T)$ represents the temperature module where $T$ is a variable that represent temperature stress (e.g. air temperature at 2 meters, or land surface temperature)

$$
f(T) = e^{-\frac{(T + b_5)^2}{2b_6^2}}
$$


Given the previous formulation we optimize the function using L-BFGS-B and a spatial moving window with 40 observations. The optimization function is defined in [udf_parameters_optim_low_res.py](https://github.com/dpabon/SIF_downscaling_CDSE/blob/main/sif_downscaling_openEO_CDSE/udf/udf_parameters_optim_low_res.py).

First we need to define the boundaries and start values for $b1$, $b2$, $b5$ $b6$ parameters:

```{python}
# the order for each variable follows: b1,b2,b3,b4,b5,b6

param_min = [0, 0.1, -310, 1]

param_ini = [1, 2, -295, 20]

param_max = [1.5, 5, -290, 50]
```


To apply the optimization function in the data cube we define an openEO User Define Function using:

```{python}
my_udf = openeo.UDF.from_file(
    "src/udf/udf_parameters_optim_low_res.py",
    context={
        "param_ini": param_ini,
        "param_min": param_min,
        "param_max": param_max,
        "min_obs": 40,
        "window_size_lat": 7,
        "window_size_lon": 7,
    },
)

```

Notice that the size of the moving window is set using ```window_size_lat``` and ```window_size_lon```.

Then we can apply our function to the data cube using:
```{python}

parameters_cube_low = dataset_SIF_low.apply_neighborhood(
    process=my_udf,
    size=[
        {"dimension": "x", "value": 512, "unit": "px"},
        {"dimension": "y", "value": 512, "unit": "px"},
    ],
    overlap=[
        {"dimension": "x", "value": 20, "unit": "px"},
        {"dimension": "y", "value": 20, "unit": "px"},
    ],
)

# changing the name of the ouput
output_bands = ["b1", "b2", "b5", "b6"]

parameters_cube_low_rename = parameters_cube_low.rename_labels("bands", output_bands)

```

and see the process graph:
```{python}
parameters_cube_low_rename
```

Now we will download the cube the optimized parameters to have a look and spatially upsample to match the Sentinel-3 cube at high resolution.

```{python}
# | eval: false
"""
parameters_cube_low_rename.execute_batch(outputfile="data/results_parameters_optim_low_resolution_iberian_peninsula.tif")
"""
```

### Checking parameter optimization results


```{python}
parameters_cube_local = rio.open_rasterio(
    "data/results_parameters_optim_low_resolution_iberian_peninsula.tif"
)
print(parameters_cube_local)
```

```{python}
# plt.clf()
fig, axs = plt.subplots(nrows=2, ncols=2, figsize=(8, 6))
axs = axs.flatten()
counter = 0
for i in [1, 2, 5, 6]:
    parameters_cube_local.isel(band=counter).plot(ax=axs[counter])
    axs[counter].set_title(f"b{i}")
    counter += 1

plt.tight_layout()
```

....

### Resampling OLCI products at 1 km

Originally the OLCI products are 300 meters resolution, as Sentinel-3 LST product is at 1 km (@tbl-predictors) we need to resample the NIRv cube:

```{python}
cube_NIRv_median_1 = cube_NIRv_median.resample_cube_spatial(
    target=cube_LST_median, method="med"
)
```

### Upsampling the parameters cube

::: {.callout-note}

Until openEO team solve the upsampling issue. For details see [CDSE discusion forum](https://forum.dataspace.copernicus.eu/t/how-to-spatial-upsampling-when-using-resample-cube-spatial/4358/6) We need to make a workaround to upsample the parameters cube.

:::

This is a temporary solution
```{python}
# | code-fold: true
# | eval: false

parameters_low = rio.open_rasterio("data/results_parameters_optim_low_resolution_iberian_peninsula.tif")

parameters_low = parameters_low.drop_vars("spatial_ref")


# LST high resolution local
nirv_high = rio.open_rasterio("data/cube_nirv_1km_mask_iberian_peninsula.tif")

nirv_high = nirv_high.drop_vars(["spatial_ref", "band"])



parameters_high = parameters_low.regrid.conservative(nirv_high)

parameters_high_2 = xr.DataArray(parameters_high.data.todense(), coords=parameters_high.coords)

# Saving the resample raster

parameters_high_2.rio.to_raster("data/results_paramaters_high_resolution_iberian_peninsula.tif")

# plotting results
# plt.clf()
fig, axs = plt.subplots(nrows=2, ncols=2, figsize=(8, 6))
axs = axs.flatten()
counter = 0
for i in [1, 2, 5, 6]:
    parameters_high_2.isel(band=counter).plot(ax=axs[counter])
    axs[counter].set_title(f"b{i}")
    counter += 1

plt.tight_layout()

```

::: {.callout-important}
Change the following path accordindly to your github repository.
:::

```{python}
# | code-fold: true
# | eval: false

output_path = "https://github.com/dpabon/SIF_downscaling_CDSE/raw/refs/heads/main/data/results_paramaters_high_resolution_iberian_peninsula.tif"
```

```{python}
# | code-fold: true
# | eval: false

# Get metadata from the raster
bbox = list(parameters_high.rio.bounds())  # [minx, miny, maxx, maxy]
epsg = "4326"
shape = [parameters_high.rio.height, parameters_high.rio.width]

# Create geometry from bbox
geom = mapping(box(*bbox))

# Create the STAC item
item = pystac.Item(
    id="results_parameters_high_resolution",
    geometry=geom,
    bbox=bbox,
    datetime=datetime.strptime(temporal_extent_prototype[0], "%Y-%m-%d"),
    properties={},
)

# Add projection extension
proj_ext = ProjectionExtension.ext(item, add_if_missing=True)
proj_ext.epsg = epsg
proj_ext.shape = shape
proj_ext.bbox = bbox

# Add EO extension
EOExtension.ext(item, add_if_missing=True)

# Add the asset
item.add_asset(
    key="parameters",
    asset=pystac.Asset(
        href=output_path,  # or use an absolute path / URL
        title="Optimized Parameters High Resolution",
        media_type="image/tiff; application=geotiff",
        extra_fields={"eo:bands": [{"name": f"b{i}"} for i in [1, 2, 5, 6]]},
    ),
)


# Save as JSON

with open("data/results_parameters_high_resolution_iberian_peninsula.json", "w") as f:
    json.dump(item.to_dict(), f, indent=2)

print(item.to_dict())

# pushing changes to the remote repo to access from openEO again

git_commit = ["git", "commit", "-m", '"Upsampling of parameters updated"', "data/results_paramaters_high_resolution_iberian_peninsula.tif", "data/results_parameters_high_resolution_iberian_peninsula.json"]

subprocess.run(git_commit)

git_push = ["git", "push"]

subprocess.run(git_push)

# plotting the resampled parameters

fig, axs = plt.subplots(nrows=2, ncols=2, figsize=(8, 8))
axs = axs.flatten()

for i in range(4):
    parameters_high.sel(band=i + 1).plot(ax=axs[i])
    axs[i].set_title(f"b{i + 1}")

plt.tight_layout()

```


Once the upsampling functionality is part of openEO one should be able to do:

```{python}
# | eval: false
"""
parameters_cube_high = parameters_cube_low_rename.resample_cube_spatial(
    target=cube_LST_median
)
"""
```

Meanwhile we can use ```load_stac``` to load again the parameters cube in openEO.


```{python}
parameters_cube_high = connection.load_stac(
    "https://raw.githubusercontent.com/dpabon/SIF_downscaling_CDSE/refs/heads/main/data/results_parameters_high_resolution_iberian_peninsula.json",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["b1", "b2", "b5", "b6"],
)
parameters_cube_high


# parameters_cube_high_median = parameters_cube_high.reduce_temporal("median")
parameters_cube_high_median = parameters_cube_high
```



Then, we can concatenate all the variables in a single cube for prediction:

```{python}
cube_to_upscale = parameters_cube_high_median.merge_cubes(cube_LST_median)

cube_to_upscale = cube_to_upscale.merge_cubes(cube_NIRv_median_1)

```

```{python}
# | eval: false
# cube_to_upscale.execute_batch(outputfile="data/sif_predictors_cube_high_iberian_peninsula.tif")
```

Checking that everything is in order with the code to upscale
```{python}
cube_to_upscale_local = xr.open_dataset("data/sif_predictors_cube_high_iberian_peninsula.tif")

print(cube_to_upscale_local)

```

```{python}

# plotting results
# plt.clf()
fig, axs = plt.subplots(nrows=3, ncols=2, figsize=(6, 9))
axs = axs.flatten()
counter = 0
for i in range(6):
    cube_to_upscale_local["band_data"].isel(band=counter).plot(ax=axs[counter])
    axs[counter].set_title(f"b{i}")
    counter += 1

plt.tight_layout()

```

### Downscaling SIF

To downscale SIF we will use @def-sif. The code implementation of @def-sif is available at [udf_sif_downscaling.py](https://github.com/dpabon/SIF_downscaling_CDSE/blob/main/sif_downscaling_openEO_CDSE/udf/udf_sif_downscaling.py). Then we can call the ```udf``` using:


```{python}
udf_sif_prediction = openeo.UDF.from_file(
    "src/udf/udf_sif_downscaling.py",
    context={"window_size_lat": 3, "window_size_lon": 3},
)

sif_downscaled = cube_to_upscale.apply_neighborhood(
    udf_sif_prediction,
    size=[
        {"dimension": "x", "value": 512, "unit": "px"},
        {"dimension": "y", "value": 512, "unit": "px"},
    ],
    overlap=[
        {"dimension": "x", "value": 20, "unit": "px"},
        {"dimension": "y", "value": 20, "unit": "px"},
    ],
)
```



It is not possible to reduce the number of bands using ```apply_neighborhood``` then we need to just select the first band:

```{python}
# removing bands that are not needed it

sif_downscaled_renamed = sif_downscaled.rename_labels(
    dimension="bands", source=["b1"], target=["SIF"]
)

sif_downscaled_renamed = sif_downscaled_renamed.band("SIF")
```

Now we can run everthing and save the results


```{python}
"""
sif_downscaled_renamed.execute_batch(
    outputfile="data/openeo_sif_downscaled_iberian_peninsula.tif",
    title="SIF_downscaling",
    description="Predicting SIF at high spatial resolution"
)
"""
```

### Comparing SIF products

Comparing the original SIF product at 5 km with the Downscaled SIF at 1 km.

```{python}
sif_downscaled_local = rio.open_rasterio("data/openeo_sif_downscaled_iberian_peninsula.tif")
print(sif_downscaled_local)
```

```{python}
fig, axs = plt.subplots(nrows=2, figsize=(6, 10))
cube_sif_local.plot(ax=axs[0], vmin = 0)
axs[0].set_title("SIF (Original)")
sif_downscaled_local.plot(ax=axs[1])
axs[1].set_title("SIF (Downscaled)")

```


To validate the downscaling results let's resample the SIF downscaled and compare it with the original product at 5 km.


```{python}

sif_downscaled_resampled = sif_downscaled_renamed.resample_cube_spatial(
    target=cube_SIF_original_median,
    method="med",
)

```

```{python}
# sif_downscaled_resampled.execute_batch("data/sif_downscaled_resampled_iberian_peninsula.tif")
```


```{python}
sif_downscaled_resampled_local = rio.open_rasterio("data/sif_downscaled_resampled_iberian_peninsula.tif")

sif_downscaled_resampled_local = sif_downscaled_resampled_local.isel(y = range(100), x = range(100))

sif_downscaled_resampled_local = sif_downscaled_resampled_local.assign_coords({'x': cube_sif_local.x.values, 'y': cube_sif_local.y.values})
```


```{python}
fig, axs = plt.subplots(nrows=2, figsize=(6, 10))
cube_sif_local.plot(ax=axs[0], vmin = 0)
axs[0].set_title("SIF (Original)")
sif_downscaled_resampled_local.plot(ax=axs[1])
axs[1].set_title("SIF (Downscaled) resampled")

plt.tight_layout()
```

Now we can compare the original SIF with the downscaled SIF + spatial resampling using $originalSIF - upscaledSIF$

```{python}
fig, axs = plt.subplots(nrows=1, figsize=(6, 6))
differences = cube_sif_local - sif_downscaled_resampled_local
differences.plot()
```


## Study number 2: Downscaling SIF in part of Indonesia

### Area of Interest and Time Period

Before going into the details of the datasets, we need to define an area of interest and time period for our analysis. For this example, we will focus on part of Indonesia during the time period between 2023-07-24 and 2023-07-31.

```{python}
spatial_extent_prototype = {
    "west": 109.0, # 114.0
    "east": 124.0, #120.0
    "south": -5.0,
    "north": 3.0,
}

temporal_extent_prototype = ["2023-07-27", "2023-07-31"]
```

```{python}
# | echo: false
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib.patches import Rectangle


def plot_world_with_bbox(bbox, title="World Map with Bounding Box"):
    """
    Plot world map with a bounding box overlay.

    Parameters:
    -----------
    bbox : tuple or list
        Bounding box coordinates as (min_lon, min_lat, max_lon, max_lat)
    title : str
        Plot title
    """
    min_lon, min_lat, max_lon, max_lat = (
        bbox["west"],
        bbox["south"],
        bbox["east"],
        bbox["north"],
    )

    # Create figure and axis with PlateCarree projection
    fig, ax = plt.subplots(
        figsize=(15, 10), subplot_kw={"projection": ccrs.PlateCarree()}
    )

    # Add map features
    ax.add_feature(cfeature.LAND, facecolor="lightgray", edgecolor="none")
    ax.add_feature(cfeature.OCEAN, facecolor="lightblue")
    ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
    ax.add_feature(cfeature.BORDERS, linewidth=0.3, linestyle=":")
    ax.add_feature(
        cfeature.LAKES, facecolor="lightblue", edgecolor="black", linewidth=0.3
    )

    # Add gridlines
    gl = ax.gridlines(
        draw_labels=True, linewidth=0.5, color="gray", alpha=0.5, linestyle="--"
    )
    gl.top_labels = False
    gl.right_labels = False

    # Set global extent
    ax.set_global()

    # Draw bounding box
    width = max_lon - min_lon
    height = max_lat - min_lat

    bbox_patch = Rectangle(
        (min_lon, min_lat),
        width,
        height,
        linewidth=2,
        edgecolor="red",
        facecolor="none",
        transform=ccrs.PlateCarree(),
        zorder=5,
    )
    ax.add_patch(bbox_patch)

    # Add a label for the bbox
    center_lon = (min_lon + max_lon) / 2
    center_lat = (min_lat + max_lat) / 2
    ax.text(
        center_lon,
        max_lat + 5,
        "Area of Interest",
        transform=ccrs.PlateCarree(),
        ha="center",
        fontsize=10,
        color="red",
        weight="bold",
    )

    ax.set_title(title, fontsize=14, weight="bold", pad=20)

    plt.tight_layout()
    return fig, ax


fig1, ax1 = plot_world_with_bbox(spatial_extent_prototype, " ")

plt.show()

```

### Connecting to CDSE using openEO

To connect to the openEO insfrastructure in the CDSE we need to create a connection:

::: {.callout-important}
If you're using Positron to run this tutorial please first open the ```authentication.ipynb``` notebook run the cells there, and follow the instructions. This step is only necessary once, the next time you run the cells of this tutorial openeo will use refresh authentication tokens.
:::

```{python}
connection = openeo.connect(
    "https://openeofed.dataspace.copernicus.eu/"
)

connection.authenticate_oidc()
```

This will open a tab in the web-browser where the user needs to authenticate using the CDSE credentials. For more details on openEO in CDSE please see: [https://dataspace.copernicus.eu/analyse/openeo](https://dataspace.copernicus.eu/analyse/openeo)

Then we can see the data collections that are available:

```{python}
# | eval: false

connection.list_collections()
```

:::{.scrolling}

```{python}
# | echo: false

connection.list_collections()
```

:::


### Variables

For this tutorial we will use the following datasets/variables:

Target:

| Variable name | Collection | Band Name | Spatial resolution|
|--|--|--|--|
|Sun-Induced Flourescence| [Dong Li SIF](https://raw.githubusercontent.com/dpabon/SIF_downscaling_CDSE/refs/heads/main/data/SIF_20180629.json)| ```SIF```| 5 km |

Currently there are two SIF gridded products derived from Sentinel-5p that are availables:

1. [S5P-PAL SIF](https://data-portal.s5p-pal.com/products/troposif.html). This product is generated by the Sentinel-5P Product Algorithm Laboratory (S5P-PAL) and contains modified Copernicus Sentinel data processed by S[&]T. Unfortunately, the current (at least at: 2025-12-01) STAC dissemination only include plain netcdf files and not cloud optimized data format. Currently the [Atmosphere Virtual Lab project](https://atmospherevirtuallab.org/) is working in provided zarr datacubes for the L3 products, including SIF.

2. [Dong LI SIF](https://www.sciencedirect.com/science/article/pii/S0034425725003918#da0005). This product uses an artificial neural network to retrieve SIF from Sentinel-5p observations. Thanks to Dong Li for provinding us with a [gridded example of the product](https://github.com/dpabon/SIF_downscaling_CDSE/blob/main/data/SIF_20180629.tif) and the [stac item](https://github.com/dpabon/SIF_downscaling_CDSE/blob/main/data/SIF_20180629.json) necessary to ingest the product in the openEO-CDSE infrastructure. This files can be found in the data directory of the [repository](https://github.com/dpabon/SIF_downscaling_CDSE).

Predictors:

| Variable name | Collection | Band Name | Spatial resolution |
|--|--|--|--|
|Land Surface Temperature| ```SENTINEL3_SLSTR_L2_LST```| ```LST```| 1 km|
|Near Infrared Vegetation Index| ```SENTINEL3_OLCI_L2_LAND```| ```RC681```, ```RC865```| 300 m|
: SIF predictors {#tbl-predictors}

#### Creating openEO datacubes for the variables

```{python}
# Testing SIF - Dong Li

cube_SIF_original_median = connection.load_stac(
    "https://raw.githubusercontent.com/dpabon/SIF_downscaling_CDSE/refs/heads/main/data/2023-07-SIF/5_days_composites/SIF_20230727_20230731.json",
    bands=["SIF"],
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
)

```


```{python}
cube_LST = connection.load_collection(
    "SENTINEL3_SLSTR_L2_LST",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["LST"],
)

cube_LST_qc = connection.load_collection(
    "SENTINEL3_SLSTR_L2_LST",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["confidence_in"],
)

red = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["RC681"],
)

nir = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["RC865"],
)

cube_NIRv = ((nir - red) / (nir + red)) * nir

cube_NIRv = cube_NIRv.rename_labels(dimension="bands", target=["NIRv"])

cube_OLCI_qc = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["LQSF"],
)

```




#### Masking clouds


```{python}

mask = cube_LST_qc > 5000

cube_LST_masked = cube_LST.mask(mask)

```

```{python}

mask_olci = cube_OLCI_qc > 10000

cube_NIRv_masked = cube_NIRv.mask(mask_olci)
```


If we call one of the cubes we can see the process graph that is created by openEO:
 
```{python}
cube_LST_masked
```

### Reducing the time dimension

For this analysis we will compute a composite of the area of interest using all the observations during the time period for all the variables except SIF that is already one time step observation.

```{python}

cube_LST_median = cube_LST_masked.reduce_temporal(reducer="max")

cube_NIRv_median = cube_NIRv_masked.reduce_temporal(reducer="median")

```

#### Resampling OLCI products at 1 km

Originally the OLCI products are 300 meters resolution, as Sentinel-3 LST product is at 1 km (@tbl-predictors) we need to resample the NIRv cube:

```{python}
cube_NIRv_median_1 = cube_NIRv_median.resample_cube_spatial(
    target=cube_LST_median, method="med"
)
```

```{python}
cube_LST_median
```

#### Resampling OLCI products at 1 km

Originally the OLCI products are 300 meters resolution, as Sentinel-3 LST product is at 1 km (@tbl-predictors) we need to resample the NIRv cube:

```{python}
cube_NIRv_median_1 = cube_NIRv_median.resample_cube_spatial(
    target=cube_LST_median, method="med"
)
```

### Inspecting the variables

Then we will inspect the products, for that we need to execute the processors for each cube, save it locally, open and plot.


```{python}
# cube_SIF_original_median.execute_batch(outputfile="data/cube_SIF_median_indonesia_example.tif")
# cube_LST_median.execute_batch(outputfile="data/cube_LST_median_indonesia_example.tif")
# cube_NIRv_median_1.execute_batch("data/cube_nirv_1km_mask_indonesia_example.tif")
```



```{python}
cube_sif_local = rio.open_rasterio(
    filename="data/cube_SIF_median_indonesia_example.tif", mask_and_scale=True
)
cube_lst_local = rio.open_rasterio(filename="data/cube_LST_median_indonesia_example.tif")
cube_nirv_local = rio.open_rasterio(filename="data/cube_nirv_1km_mask_indonesia_example.tif")

```

```{python}
fig, axs = plt.subplots(nrows=3, figsize=(10, 15))
cube_sif_local.plot(ax=axs[0], vmin=0)
axs[0].set_title("SIF")
cube_lst_local.plot(ax=axs[1])
axs[1].set_title("LST")
cube_nirv_local.plot(ax=axs[2])
axs[2].set_title("NIRv")

plt.tight_layout()

```



### Spatial resampling to match the SIF resolution product


```{python}
cube_LST_median_low = cube_LST_median.resample_cube_spatial(
    target=cube_SIF_original_median, method="med"
)

cube_NIRv_median_low = cube_NIRv_median.resample_cube_spatial(
    target=cube_SIF_original_median, method="med"
)

```


```{python}
cube_LST_median_low
```

Merging all the cubes at low resolution (SIF original resolution)

```{python}
dataset_SIF_low = cube_SIF_original_median.merge_cubes(cube_LST_median_low)

dataset_SIF_low = dataset_SIF_low.merge_cubes(cube_NIRv_median_low)

```



Adding two dummy variables to the datacube to match the number of oputput parameters of the optimization function.

```{python}
dataset_SIF_low = dataset_SIF_low.merge_cubes(
    other=cube_SIF_original_median.rename_labels(dimension="bands", target=["dummy_1"])
)
dataset_SIF_low = dataset_SIF_low.merge_cubes(
    other=cube_SIF_original_median.rename_labels(dimension="bands", target=["dummy_2"])
)
```



```{python}
# | eval: false
# dataset_SIF_low.execute_batch(outputfile="data/sif_predictors_cube_low_indonesia_example.nc")
```

Let's check the cube after resampling

```{python}
dataset_sif_low_local = xr.open_dataset("data/sif_predictors_cube_low_indonesia_example.nc")
print(dataset_sif_low_local)
```

```{python}
fig, axs = plt.subplots(nrows=3, figsize=(18, 15))
dataset_sif_low_local["SIF"].plot(ax=axs[0], vmin = 0)
axs[0].set_title("SIF")
dataset_sif_low_local["LST"].plot(ax=axs[1])
axs[1].set_title("LST")
dataset_sif_low_local["NIRv"].plot(ax=axs[2])
axs[2].set_title("NIRv")
plt.tight_layout()

```


### SIF parameter optimization at low spatial resolution

To predict SIF we use the following formulation:

::: {#def-sif}
$$SIF = f(V) \cdot f(T)$$
:::

where $f(V)$ represents the vegetation module and $V$ is a vegation index: 
$$f(V) = b_2 \cdot V^{b_1}$$


$f(T)$ represents the temperature module where $T$ is a variable that represent temperature stress (e.g. air temperature at 2 meters, or land surface temperature)

$$
f(T) = e^{-\frac{(T + b_5)^2}{2b_6^2}}
$$


Given the previous formulation we optimize the function using L-BFGS-B and a spatial moving window with 40 observations. The optimization function is defined in [udf_parameters_optim_low_res.py](https://github.com/dpabon/SIF_downscaling_CDSE/blob/main/sif_downscaling_openEO_CDSE/udf/udf_parameters_optim_low_res.py).

First we need to define the boundaries and start values for $b1$, $b2$, $b5$ $b6$ parameters:

```{python}
# the order for each variable follows: b1,b2,b3,b4,b5,b6

param_min = [0, 0.1, -310, 1]

param_ini = [1, 2, -295, 20]

param_max = [1.5, 5, -290, 50]
```


To apply the optimization function in the data cube we define an openEO User Define Function using:

```{python}
my_udf = openeo.UDF.from_file(
    "src/udf/udf_parameters_optim_low_res.py",
    context={
        "param_ini": param_ini,
        "param_min": param_min,
        "param_max": param_max,
        "min_obs": 40,
        "window_size_lat": 7,
        "window_size_lon": 7,
    },
)

```

Notice that the size of the moving window is set using ```window_size_lat``` and ```window_size_lon```.

Then we can apply our function to the data cube using:
```{python}

parameters_cube_low = dataset_SIF_low.apply_neighborhood(
    process=my_udf,
    size=[
        {"dimension": "x", "value": 512, "unit": "px"},
        {"dimension": "y", "value": 512, "unit": "px"},
    ],
    overlap=[
        {"dimension": "x", "value": 20, "unit": "px"},
        {"dimension": "y", "value": 20, "unit": "px"},
    ],
)

# changing the name of the ouput
output_bands = ["b1", "b2", "b5", "b6"]

parameters_cube_low_rename = parameters_cube_low.rename_labels("bands", output_bands)

```

and see the process graph:
```{python}
parameters_cube_low_rename
```

Now we will download the cube the optimized parameters to have a look and spatially upsample to match the Sentinel-3 cube at high resolution.

```{python}
# | eval: false
"""
parameters_cube_low_rename.execute_batch(outputfile="data/results_parameters_optim_low_resolution_indonesia_example.tif")
"""
```

### Checking parameter optimization results


```{python}
parameters_cube_local = rio.open_rasterio(
    "data/results_parameters_optim_low_resolution_indonesia_example.tif"
)
print(parameters_cube_local)
```

```{python}
# plt.clf()
fig, axs = plt.subplots(nrows=2, ncols=2, figsize=(8, 6))
axs = axs.flatten()
counter = 0
for i in [1, 2, 5, 6]:
    parameters_cube_local.isel(band=counter).plot(ax=axs[counter])
    axs[counter].set_title(f"b{i}")
    counter += 1

plt.tight_layout()
```

....

### Resampling OLCI products at 1 km

Originally the OLCI products are 300 meters resolution, as Sentinel-3 LST product is at 1 km (@tbl-predictors) we need to resample the NIRv cube:

```{python}
cube_NIRv_median_1 = cube_NIRv_median.resample_cube_spatial(
    target=cube_LST_median, method="med"
)
```

### Upsampling the parameters cube

::: {.callout-note}

Until openEO team solve the upsampling issue. For details see [CDSE discusion forum](https://forum.dataspace.copernicus.eu/t/how-to-spatial-upsampling-when-using-resample-cube-spatial/4358/6) We need to make a workaround to upsample the parameters cube.

:::

This is a temporary solution
```{python}
# | code-fold: true
# | eval: false

parameters_low = rio.open_rasterio("data/results_parameters_optim_low_resolution_indonesia_example.tif")

parameters_low = parameters_low.drop_vars("spatial_ref")


# LST high resolution local
nirv_high = rio.open_rasterio("data/cube_nirv_1km_mask_indonesia_example.tif")

nirv_high = nirv_high.drop_vars(["spatial_ref", "band"])



parameters_high = parameters_low.regrid.conservative(nirv_high)

parameters_high_2 = xr.DataArray(parameters_high.data.todense(), coords=parameters_high.coords)

# Saving the resample raster

parameters_high_2.rio.to_raster("data/results_paramaters_high_resolution_indonesia_example.tif")

# plotting results
# plt.clf()
fig, axs = plt.subplots(nrows=2, ncols=2, figsize=(8, 6))
axs = axs.flatten()
counter = 0
for i in [1, 2, 5, 6]:
    parameters_high_2.isel(band=counter).plot(ax=axs[counter])
    axs[counter].set_title(f"b{i}")
    counter += 1

plt.tight_layout()

```

::: {.callout-important}
Change the following path accordindly to your github repository.
:::

```{python}
# | code-fold: true
# | eval: false

output_path = "https://github.com/dpabon/SIF_downscaling_CDSE/raw/refs/heads/main/data/results_paramaters_high_resolution_indonesia_example.tif"
```

```{python}
# | code-fold: true
# | eval: false

# Get metadata from the raster
bbox = list(parameters_high.rio.bounds())  # [minx, miny, maxx, maxy]
epsg = "4326"
shape = [parameters_high.rio.height, parameters_high.rio.width]

# Create geometry from bbox
geom = mapping(box(*bbox))

# Create the STAC item
item = pystac.Item(
    id="results_parameters_high_resolution",
    geometry=geom,
    bbox=bbox,
    datetime=datetime.strptime(temporal_extent_prototype[0], "%Y-%m-%d"),
    properties={},
)

# Add projection extension
proj_ext = ProjectionExtension.ext(item, add_if_missing=True)
proj_ext.epsg = epsg
proj_ext.shape = shape
proj_ext.bbox = bbox

# Add EO extension
EOExtension.ext(item, add_if_missing=True)

# Add the asset
item.add_asset(
    key="parameters",
    asset=pystac.Asset(
        href=output_path,  # or use an absolute path / URL
        title="Optimized Parameters High Resolution",
        media_type="image/tiff; application=geotiff",
        extra_fields={"eo:bands": [{"name": f"b{i}"} for i in [1, 2, 5, 6]]},
    ),
)


# Save as JSON

with open("data/results_parameters_high_resolution_indonesia_example.json", "w") as f:
    json.dump(item.to_dict(), f, indent=2)

print(item.to_dict())

# pushing changes to the remote repo to access from openEO again

git_commit = ["git", "commit", "-m", '"Upsampling of parameters updated"', "data/results_paramaters_high_resolution_indonesia_example.tif", "data/results_parameters_high_resolution_indonesia_example.json"]

subprocess.run(git_commit)

git_push = ["git", "push"]

subprocess.run(git_push)

# plotting the resampled parameters

fig, axs = plt.subplots(nrows=2, ncols=2, figsize=(8, 8))
axs = axs.flatten()

for i in range(4):
    parameters_high.sel(band=i + 1).plot(ax=axs[i])
    axs[i].set_title(f"b{i + 1}")

plt.tight_layout()

```


Once the upsampling functionality is part of openEO one should be able to do:

```{python}
# | eval: false
"""
parameters_cube_high = parameters_cube_low_rename.resample_cube_spatial(
    target=cube_LST_median
)
"""
```

Meanwhile we can use ```load_stac``` to load again the parameters cube in openEO.


```{python}
parameters_cube_high = connection.load_stac(
    "https://raw.githubusercontent.com/dpabon/SIF_downscaling_CDSE/refs/heads/main/data/results_parameters_high_resolution_indonesia_example.json",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["b1", "b2", "b5", "b6"],
)
parameters_cube_high


# parameters_cube_high_median = parameters_cube_high.reduce_temporal("median")
parameters_cube_high_median = parameters_cube_high
```



Then, we can concatenate all the variables in a single cube for prediction:

```{python}
cube_to_upscale = parameters_cube_high_median.merge_cubes(cube_LST_median)

cube_to_upscale = cube_to_upscale.merge_cubes(cube_NIRv_median_1)

```

```{python}
# | eval: false
# cube_to_upscale.execute_batch(outputfile="data/sif_predictors_cube_high_indonesia_example.tif")
```

Checking that everything is in order with the code to upscale
```{python}
cube_to_upscale_local = xr.open_dataset("data/sif_predictors_cube_high_indonesia_example.tif")

print(cube_to_upscale_local)

```

```{python}

# plotting results
# plt.clf()
fig, axs = plt.subplots(nrows=3, ncols=2, figsize=(8, 6))
axs = axs.flatten()
counter = 0
for i in range(6):
    cube_to_upscale_local["band_data"].isel(band=counter).plot(ax=axs[counter])
    axs[counter].set_title(f"b{i}")
    counter += 1

plt.tight_layout()

```

### Downscaling SIF

To downscale SIF we will use @def-sif. The code implementation of @def-sif is available at [udf_sif_downscaling.py](https://github.com/dpabon/SIF_downscaling_CDSE/blob/main/sif_downscaling_openEO_CDSE/udf/udf_sif_downscaling.py). Then we can call the ```udf``` using:


```{python}
udf_sif_prediction = openeo.UDF.from_file(
    "src/udf/udf_sif_downscaling.py",
    context={"window_size_lat": 3, "window_size_lon": 3},
)

sif_downscaled = cube_to_upscale.apply_neighborhood(
    udf_sif_prediction,
    size=[
        {"dimension": "x", "value": 512, "unit": "px"},
        {"dimension": "y", "value": 512, "unit": "px"},
    ],
    overlap=[
        {"dimension": "x", "value": 20, "unit": "px"},
        {"dimension": "y", "value": 20, "unit": "px"},
    ],
)
```



It is not possible to reduce the number of bands using ```apply_neighborhood``` then we need to just select the first band:

```{python}
# removing bands that are not needed it

sif_downscaled_renamed = sif_downscaled.rename_labels(
    dimension="bands", source=["b1"], target=["SIF"]
)

sif_downscaled_renamed = sif_downscaled_renamed.band("SIF")
```

Now we can run everthing and save the results


```{python}
"""
sif_downscaled_renamed.execute_batch(
    outputfile="data/openeo_sif_downscaled_indonesia_example.tif",
    title="SIF_downscaling",
    description="Predicting SIF at high spatial resolution"
)
"""
```

### Comparing SIF products

Comparing the original SIF product at 5 km with the Downscaled SIF at 1 km.

```{python}
sif_downscaled_local = rio.open_rasterio("data/openeo_sif_downscaled_indonesia_example.tif")
print(sif_downscaled_local)
```

```{python}
fig, axs = plt.subplots(nrows=2, figsize=(6, 10))
cube_sif_local.plot(ax=axs[0], vmin = 0)
axs[0].set_title("SIF (Original)")
sif_downscaled_local.plot(ax=axs[1])
axs[1].set_title("SIF (Downscaled)")

```


To validate the downscaling results let's resample the SIF downscaled and compare it with the original product at 5 km.


```{python}

sif_downscaled_resampled = sif_downscaled_renamed.resample_cube_spatial(
    target=cube_SIF_original_median,
    method="med",
)

```

```{python}
# sif_downscaled_resampled.execute_batch("data/sif_downscaled_resampled_indonesia_example.tif")
```


```{python}
sif_downscaled_resampled_local = rio.open_rasterio("data/sif_downscaled_resampled_indonesia_example.tif")

sif_downscaled_resampled_local = sif_downscaled_resampled_local.isel(y = range(80), x = range(0,150))

sif_downscaled_resampled_local = sif_downscaled_resampled_local.assign_coords({'x': cube_sif_local.x.values, 'y': cube_sif_local.y.values})
```


```{python}
fig, axs = plt.subplots(nrows=2, figsize=(6, 10))
cube_sif_local.plot(ax=axs[0], vmin = 0)
axs[0].set_title("SIF (Original)")
sif_downscaled_resampled_local.plot(ax=axs[1])
axs[1].set_title("SIF (Downscaled) resampled")

plt.tight_layout()
```

Now we can compare the original SIF with the downscaled SIF + spatial resampling using $originalSIF - upscaledSIF$

```{python}
fig, axs = plt.subplots(nrows=1, figsize=(6, 6))
differences = cube_sif_local - sif_downscaled_resampled_local
differences.plot()
```


## Study number 3: Downscaling dcSIF (8-day, 0.05°) in the Pannonian Basin

This study applies the same workflow to a third region and replaces the SIF input with a different gridded product: daily-corrected SIF (dcSIF) as an 8-day composite at 0.05°. The processing chain (masking, compositing, resampling, parameter optimization, upsampling workaround and prediction) is the same as in the previous studies.

| | Study 1 and 2 | Study 3 |
|--|--|--|
| SIF input | Dong Li SIF, 5-day composite, 0.1° | dcSIF, 8-day composite, 0.05° |
| Region | Iberian Peninsula / Indonesia | Pannonian Basin (Hungary and surroundings) |
| Time window | 5 days | 2023-07-20 to 2023-07-27 |
: Differences between Study 3 and the previous studies {#tbl-study3-differences}

### Why the Pannonian Basin

The parameters are fitted in a moving window, and each window needs enough cells where SIF, NIRv and LST are valid at the same time. In practice the limiting factor is cloud cover in the Sentinel-3 OLCI observations used for NIRv. A test over East China (116–123.8° E, 28.3–33.7° N) in late July 2023 showed that only about half of the land had a valid NIRv composite after cloud masking, and the fitted parameters covered only a fraction of the region. For the same period, the Pannonian Basin has an almost complete clear-sky NIRv composite, lies entirely over land, and shows strong spatial contrasts (Great Hungarian Plain, hills and forests, irrigated and rainfed croplands), which is where downscaling adds most information.

### Area of Interest and Time Period

```{python}
spatial_extent_prototype = {
    "west": 16.0,
    "east": 23.0,
    "south": 45.5,
    "north": 48.5,
}

# The end date is exclusive in openEO: "2023-07-28" covers the full 8-day window.
temporal_extent_prototype = ["2023-07-20", "2023-07-28"]
```

```{python}
# | echo: false
fig1, ax1 = plot_world_with_bbox(spatial_extent_prototype, " ")
plt.show()
```

### Variables

Target:

| Variable name | Source | Band Name | Spatial resolution | Temporal resolution |
|--|--|--|--|--|
| Sun-Induced Fluorescence, daily corrected (dcSIF) | TROPOMI, gridded | ```SIF``` | 0.05° | 8 days |
: dcSIF target {#tbl-study3-target}

<!-- TODO: add the reference of the SIF retrieval and the Zenodo DOI of the gridded dcSIF product -->

The dcSIF product was gridded from TROPOMI Level-2 observations to 0.05° 8-day composites with the oversampling approach implemented in SatelliteGridding.jl (C. Frankenberg). The 8-day windows start on 1 January of each year; the window used here (2023-07-20 to 2023-07-27) is time step 26 of 2023. The predictors are the same as in the previous studies (@tbl-predictors).

#### Preparing dcSIF for openEO

The gridded dcSIF product is distributed as yearly NetCDF files (dimensions `lat`, `lon`, `time`). `load_stac` needs a raster file at a public URL described by a STAC item, so the 8-day time step was extracted, cropped to the area of interest plus a 1° margin, written as a Cloud-Optimized GeoTIFF, and described with a STAC item following the structure of the other items in the `data` directory:

```{python}
# | code-fold: true
# | eval: false

from datetime import timedelta

NC_PATH = "/path/to/dcSIF_2023_file.nc"  # yearly NetCDF, 0.05 deg, 8-day
WINDOW_START = "2023-07-20"
WINDOW_DAYS = 8
BUFFER_DEG = 1.0
NODATA = -9999.0

t0 = datetime.strptime(WINDOW_START, "%Y-%m-%d")
t1 = t0 + timedelta(days=WINDOW_DAYS - 1)
tag = f"{t0:%Y%m%d}_{t1:%Y%m%d}"
f_tif = f"data/2023-07-dcSIF/dcSIF_8day_{tag}_pannonian_basin.tif"
f_json = f"data/2023-07-dcSIF/dcSIF_8day_{tag}_pannonian_basin.json"
tif_url = f"https://github.com/dpabon/SIF_downscaling_CDSE/raw/refs/heads/main/{f_tif}"

# Select the time step and crop (lazy: only the subset is read)
ds = xr.open_dataset(NC_PATH)
sel_time = ds.time.sel(time=np.datetime64(WINDOW_START), method="nearest").values
da = ds["sif_dc"].sel(time=sel_time)
da = da.sel(
    lon=slice(spatial_extent_prototype["west"] - BUFFER_DEG,
              spatial_extent_prototype["east"] + BUFFER_DEG),
    lat=slice(spatial_extent_prototype["south"] - BUFFER_DEG,
              spatial_extent_prototype["north"] + BUFFER_DEG),  # lat is ascending
)

# North-up orientation, x/y naming, clean float64 coordinates
da = da.transpose("lat", "lon").load().sortby("lat", ascending=False)
da = da.rename({"lat": "y", "lon": "x"}).drop_vars("time", errors="ignore").astype("float32")
da = da.assign_coords(
    x=np.round(da.x.values.astype("float64"), 4),
    y=np.round(da.y.values.astype("float64"), 4),
)

# Cloud-Optimized GeoTIFF
da = da.fillna(NODATA).rio.write_crs("EPSG:4326").rio.write_nodata(NODATA)
da.rio.to_raster(f_tif, driver="COG", compress="DEFLATE")

# STAC item
bbox = [float(b) for b in da.rio.bounds()]
item = pystac.Item(
    id=f"dcSIF_8day_{tag}_pannonian_basin",
    geometry=mapping(box(*bbox)),
    bbox=bbox,
    datetime=t0 + timedelta(days=WINDOW_DAYS / 2),
    properties={
        "start_datetime": f"{t0:%Y-%m-%d}T00:00:00Z",
        "end_datetime": f"{t1:%Y-%m-%d}T23:59:59Z",
    },
)
proj_ext = ProjectionExtension.ext(item, add_if_missing=True)
proj_ext.shape = [int(da.rio.height), int(da.rio.width)]
proj_ext.bbox = bbox
EOExtension.ext(item, add_if_missing=True)
item.add_asset(
    key="SIF",
    asset=pystac.Asset(
        href=tif_url,
        title=f"dcSIF 8-day composite {t0:%Y-%m-%d} to {t1:%Y-%m-%d} (0.05 deg)",
        media_type="image/tiff; application=geotiff; profile=cloud-optimized",
        extra_fields={"eo:bands": [{"name": "SIF", "nodata": NODATA}]},
    ),
)

item_dict = item.to_dict()
# Same projection fields as the other items (newer pystac versions write proj:code)
item_dict["properties"].pop("proj:code", None)
item_dict["properties"]["proj:epsg"] = 4326
item_dict["stac_extensions"] = [
    "https://stac-extensions.github.io/eo/v1.1.0/schema.json",
    "https://stac-extensions.github.io/projection/v1.1.0/schema.json",
]
with open(f_json, "w") as f:
    json.dump(item_dict, f, indent=2)
```

For this time step dcSIF is fully valid over the area of interest, with a median of 0.64 and 1st/99th percentiles of 0.31/0.89. This is the same order of magnitude as the Dong Li SIF product, so the parameter bounds of the previous studies are kept.

#### Creating openEO datacubes for the variables

::: {.callout-note}
The preflight validation of the openEO back-end sometimes fails with `CollectionNotFound` for `SENTINEL3_SLSTR_L2_LST` or `SENTINEL3_OLCI_L2_LAND`, although both collections exist. This is intermittent: resubmitting the job, or connecting directly to the CDSE back-end (`https://openeo.dataspace.copernicus.eu/`), solves it.
:::

```{python}
cube_SIF_original_median = connection.load_stac(
    "https://raw.githubusercontent.com/dpabon/SIF_downscaling_CDSE/refs/heads/main/data/2023-07-dcSIF/dcSIF_8day_20230720_20230727_pannonian_basin.json",
    bands=["SIF"],
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
)

cube_LST = connection.load_collection(
    "SENTINEL3_SLSTR_L2_LST",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["LST"],
)

cube_LST_qc = connection.load_collection(
    "SENTINEL3_SLSTR_L2_LST",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["confidence_in"],
)

red = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["RC681"],
)

nir = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["RC865"],
)

cube_NIRv = ((nir - red) / (nir + red)) * nir

cube_NIRv = cube_NIRv.rename_labels(dimension="bands", target=["NIRv"])

cube_OLCI_qc = connection.load_collection(
    "SENTINEL3_OLCI_L2_LAND",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["LQSF"],
)
```

#### Masking clouds, reducing the time dimension and resampling OLCI at 1 km

```{python}
cube_LST_masked = cube_LST.mask(cube_LST_qc > 5000)
cube_NIRv_masked = cube_NIRv.mask(cube_OLCI_qc > 10000)

cube_LST_median = cube_LST_masked.reduce_temporal(reducer="max")
cube_NIRv_median = cube_NIRv_masked.reduce_temporal(reducer="median")

cube_NIRv_median_1 = cube_NIRv_median.resample_cube_spatial(
    target=cube_LST_median, method="med"
)
```

### Inspecting the variables

```{python}
# | eval: false
cube_SIF_original_median.execute_batch(outputfile="data/cube_SIF_median_pannonian_basin_dcsif.tif")
cube_LST_median.execute_batch(outputfile="data/cube_LST_median_pannonian_basin_dcsif.tif")
cube_NIRv_median_1.execute_batch(outputfile="data/cube_nirv_1km_mask_pannonian_basin_dcsif.tif")
```

```{python}
cube_sif_local = rio.open_rasterio(
    filename="data/cube_SIF_median_pannonian_basin_dcsif.tif", mask_and_scale=True
)
cube_lst_local = rio.open_rasterio(filename="data/cube_LST_median_pannonian_basin_dcsif.tif")
cube_nirv_local = rio.open_rasterio(filename="data/cube_nirv_1km_mask_pannonian_basin_dcsif.tif")

fig, axs = plt.subplots(nrows=3, figsize=(7, 14))
cube_sif_local.plot(ax=axs[0], vmin=0)
axs[0].set_title("dcSIF (0.05°)")
cube_lst_local.plot(ax=axs[1])
axs[1].set_title("LST (1 km)")
cube_nirv_local.plot(ax=axs[2])
axs[2].set_title("NIRv (1 km)")
plt.tight_layout()
```

### Spatial resampling to match the SIF resolution product

```{python}
cube_LST_median_low = cube_LST_median.resample_cube_spatial(
    target=cube_SIF_original_median, method="med"
)

cube_NIRv_median_low = cube_NIRv_median.resample_cube_spatial(
    target=cube_SIF_original_median, method="med"
)

dataset_SIF_low = cube_SIF_original_median.merge_cubes(cube_LST_median_low)
dataset_SIF_low = dataset_SIF_low.merge_cubes(cube_NIRv_median_low)

# dummy variables to match the number of output parameters
dataset_SIF_low = dataset_SIF_low.merge_cubes(
    other=cube_SIF_original_median.rename_labels(dimension="bands", target=["dummy_1"])
)
dataset_SIF_low = dataset_SIF_low.merge_cubes(
    other=cube_SIF_original_median.rename_labels(dimension="bands", target=["dummy_2"])
)
```

::: {.callout-warning}
**Sensitivity of the aggregation to data gaps.** NIRv is aggregated from 300 m to the SIF grid with `method="med"`. In the East China test this dropped SIF-grid cells containing many masked (cloudy) OLCI pixels: at 0.1° the valid NIRv fraction fell from 0.49 (1 km NIRv averaged locally) to 0.15, and the fitted parameters became very sparse. Aggregating the 1 km NIRv (`cube_NIRv_median_1`) with `method="average"` recovered most of the coverage. In mostly clear-sky regions such as the Pannonian Basin the original approach works, but in cloudy regions it is worth checking the valid fraction of the low-resolution predictors before running the optimization.
:::

Checking the cube after resampling, including the fraction of cells where SIF, LST and NIRv are all valid:

```{python}
# | eval: false
dataset_SIF_low.execute_batch(outputfile="data/sif_predictors_cube_low_pannonian_basin_dcsif.nc")
```

```{python}
dataset_sif_low_local = xr.open_dataset("data/sif_predictors_cube_low_pannonian_basin_dcsif.nc")

valid = {name: dataset_sif_low_local[name].notnull() for name in ["SIF", "LST", "NIRv"]}
valid["All three"] = valid["SIF"] & valid["LST"] & valid["NIRv"]
for name, m in valid.items():
    print(f"{name:10s} valid fraction: {float(m.mean()):.2f}")

fig, axs = plt.subplots(nrows=3, figsize=(7, 14))
for ax, name in zip(axs, ["SIF", "LST", "NIRv"]):
    dataset_sif_low_local[name].squeeze().plot(ax=ax)
    ax.set_title(f"{name} at the dcSIF grid")
plt.tight_layout()
```

### SIF parameter optimization at low spatial resolution

We use the same formulation (@def-sif), parameter bounds and optimization function as in the previous studies:

```{python}
param_min = [0, 0.1, -310, 1]
param_ini = [1, 2, -295, 20]
param_max = [1.5, 5, -290, 50]

my_udf = openeo.UDF.from_file(
    "src/udf/udf_parameters_optim_low_res.py",
    context={
        "param_ini": param_ini,
        "param_min": param_min,
        "param_max": param_max,
        "min_obs": 40,
        "window_size_lat": 7,
        "window_size_lon": 7,
    },
)

parameters_cube_low = dataset_SIF_low.apply_neighborhood(
    process=my_udf,
    size=[
        {"dimension": "x", "value": 512, "unit": "px"},
        {"dimension": "y", "value": 512, "unit": "px"},
    ],
    overlap=[
        {"dimension": "x", "value": 20, "unit": "px"},
        {"dimension": "y", "value": 20, "unit": "px"},
    ],
)

parameters_cube_low_rename = parameters_cube_low.rename_labels(
    "bands", ["b1", "b2", "b5", "b6"]
)
```

Notice that `window_size_lat = window_size_lon = 7` means a window of 15 × 15 grid cells. At the 0.05° resolution of dcSIF this is 0.75° (about 80 km in latitude), half the spatial support of the same setting on the 0.1° grid of the previous studies.

```{python}
# | eval: false
parameters_cube_low_rename.execute_batch(
    outputfile="data/results_parameters_optim_low_resolution_pannonian_basin_dcsif.tif"
)
```

### Checking parameter optimization results

```{python}
parameters_cube_local = rio.open_rasterio(
    "data/results_parameters_optim_low_resolution_pannonian_basin_dcsif.tif", masked=True
)

fig, axs = plt.subplots(nrows=2, ncols=2, figsize=(10, 7))
for k, (ax, name) in enumerate(zip(axs.flatten(), ["b1", "b2", "b5", "b6"])):
    parameters_cube_local.isel(band=k).plot(ax=ax)
    ax.set_title(name)
plt.tight_layout()

# Fraction of fitted cells and of parameters at the bounds
fitted = parameters_cube_local.isel(band=0).notnull().values
print(f"Fitted fraction: {fitted.mean():.2f}")
for k, name in enumerate(["b1", "b2", "b5", "b6"]):
    x = parameters_cube_local.isel(band=k).values[fitted]
    at_lo = np.isclose(x, param_min[k], atol=1e-3).mean()
    at_hi = np.isclose(x, param_max[k], atol=1e-3).mean()
    print(f"{name}: at lower bound {at_lo:.2f}, at upper bound {at_hi:.2f}")
```

### Upsampling the parameters cube

Same workaround as in the previous studies: the parameters are upsampled locally to the 1 km NIRv grid, published with a STAC item, and loaded again with `load_stac`.

```{python}
# | code-fold: true
# | eval: false

parameters_low = rio.open_rasterio(
    "data/results_parameters_optim_low_resolution_pannonian_basin_dcsif.tif"
).drop_vars("spatial_ref")

nirv_high = rio.open_rasterio("data/cube_nirv_1km_mask_pannonian_basin_dcsif.tif")
nirv_high = nirv_high.drop_vars(["spatial_ref", "band"])

parameters_high = parameters_low.regrid.conservative(nirv_high)

data_high = parameters_high.data
if hasattr(data_high, "todense"):
    data_high = data_high.todense()

parameters_high_2 = xr.DataArray(
    data_high, coords=parameters_high.coords, dims=parameters_high.dims
)
parameters_high_2 = parameters_high_2.rio.write_crs("EPSG:4326")
parameters_high_2.rio.to_raster(
    "data/results_paramaters_high_resolution_pannonian_basin_dcsif.tif"
)
```

::: {.callout-important}
Change the following path accordingly to your github repository.
:::

```{python}
# | code-fold: true
# | eval: false

output_path = "https://github.com/dpabon/SIF_downscaling_CDSE/raw/refs/heads/main/data/results_paramaters_high_resolution_pannonian_basin_dcsif.tif"

bbox = list(parameters_high_2.rio.bounds())
shape = [parameters_high_2.rio.height, parameters_high_2.rio.width]

item = pystac.Item(
    id="results_parameters_high_resolution_pannonian_basin_dcsif",
    geometry=mapping(box(*bbox)),
    bbox=bbox,
    datetime=datetime.strptime(temporal_extent_prototype[0], "%Y-%m-%d"),
    properties={},
)

proj_ext = ProjectionExtension.ext(item, add_if_missing=True)
proj_ext.epsg = 4326
proj_ext.shape = shape
proj_ext.bbox = bbox

EOExtension.ext(item, add_if_missing=True)

item.add_asset(
    key="parameters",
    asset=pystac.Asset(
        href=output_path,
        title="Optimized Parameters High Resolution",
        media_type="image/tiff; application=geotiff",
        extra_fields={"eo:bands": [{"name": f"b{i}"} for i in [1, 2, 5, 6]]},
    ),
)

with open("data/results_parameters_high_resolution_pannonian_basin_dcsif.json", "w") as f:
    json.dump(item.to_dict(), f, indent=2)

# New files need to be added before they can be committed
files = [
    "data/results_paramaters_high_resolution_pannonian_basin_dcsif.tif",
    "data/results_parameters_high_resolution_pannonian_basin_dcsif.json",
]
subprocess.run(["git", "add", *files], check=True)
subprocess.run(["git", "commit", "-m", "Upsampled parameters Pannonian Basin dcSIF", *files], check=True)
subprocess.run(["git", "push"], check=True)
```

Loading the parameters cube again in openEO and concatenating all the variables for prediction:

```{python}
parameters_cube_high = connection.load_stac(
    "https://raw.githubusercontent.com/dpabon/SIF_downscaling_CDSE/refs/heads/main/data/results_parameters_high_resolution_pannonian_basin_dcsif.json",
    spatial_extent=spatial_extent_prototype,
    temporal_extent=temporal_extent_prototype,
    bands=["b1", "b2", "b5", "b6"],
)

cube_to_upscale = parameters_cube_high.merge_cubes(cube_LST_median)
cube_to_upscale = cube_to_upscale.merge_cubes(cube_NIRv_median_1)
```

### Downscaling SIF

```{python}
udf_sif_prediction = openeo.UDF.from_file(
    "src/udf/udf_sif_downscaling.py",
    context={"window_size_lat": 3, "window_size_lon": 3},
)

sif_downscaled = cube_to_upscale.apply_neighborhood(
    udf_sif_prediction,
    size=[
        {"dimension": "x", "value": 512, "unit": "px"},
        {"dimension": "y", "value": 512, "unit": "px"},
    ],
    overlap=[
        {"dimension": "x", "value": 20, "unit": "px"},
        {"dimension": "y", "value": 20, "unit": "px"},
    ],
)

sif_downscaled_renamed = sif_downscaled.rename_labels(
    dimension="bands", source=["b1"], target=["SIF"]
)
sif_downscaled_renamed = sif_downscaled_renamed.band("SIF")
```

```{python}
# | eval: false
sif_downscaled_renamed.execute_batch(
    outputfile="data/openeo_sif_downscaled_pannonian_basin_dcsif.tif",
    title="SIF_downscaling",
    description="Predicting SIF at high spatial resolution",
)
```

### Comparing SIF products

```{python}
sif_downscaled_local = rio.open_rasterio("data/openeo_sif_downscaled_pannonian_basin_dcsif.tif")

fig, axs = plt.subplots(nrows=2, figsize=(8, 11))
cube_sif_local.plot(ax=axs[0], vmin=0)
axs[0].set_title("dcSIF (0.05°, original)")
sif_downscaled_local.plot(ax=axs[1], vmin=0)
axs[1].set_title("SIF (1 km, downscaled)")
plt.tight_layout()
```

To check the downscaling, we aggregate the downscaled SIF back to the original dcSIF grid:

```{python}
# | eval: false
sif_downscaled_resampled = sif_downscaled_renamed.resample_cube_spatial(
    target=cube_SIF_original_median, method="med"
)
sif_downscaled_resampled.execute_batch(
    outputfile="data/sif_downscaled_resampled_pannonian_basin_dcsif.tif"
)
```

::: {.callout-tip}
The batch job above re-runs the whole processing chain before aggregating. The same aggregation can be done locally from the downloaded 1 km result:

```python
from rasterio.enums import Resampling

sif_ds = rio.open_rasterio(
    "data/openeo_sif_downscaled_pannonian_basin_dcsif.tif", masked=True
).squeeze().rio.write_nodata(np.nan)
sif_ds_res = sif_ds.rio.reproject_match(cube_sif_local.squeeze(), resampling=Resampling.average)
sif_ds_res.rio.to_raster("data/sif_downscaled_resampled_pannonian_basin_dcsif.tif")
```
:::

Comparing the original SIF with the downscaled + aggregated SIF using $originalSIF - upscaledSIF$, with summary statistics over the cells valid in both:

```{python}
sif_orig = cube_sif_local.squeeze()
sif_agg = rio.open_rasterio(
    "data/sif_downscaled_resampled_pannonian_basin_dcsif.tif", mask_and_scale=True
).squeeze()
sif_agg = sif_agg.rio.reproject_match(sif_orig)

differences = sif_orig - sif_agg

both = (sif_orig.notnull() & sif_agg.notnull()).values
o = sif_orig.values[both]
d = sif_agg.values[both]
print(f"Common valid cells: {both.sum()}")
print(f"Bias (original - aggregated): {np.mean(o - d):.3f}")
print(f"RMSE: {np.sqrt(np.mean((o - d) ** 2)):.3f}")
print(f"Pearson r: {np.corrcoef(o, d)[0, 1]:.3f}")

fig, axs = plt.subplots(2, 2, figsize=(12, 10))
sif_orig.plot(ax=axs[0, 0], vmin=0)
axs[0, 0].set_title("dcSIF (original)")
sif_agg.plot(ax=axs[0, 1], vmin=0)
axs[0, 1].set_title("SIF (downscaled, aggregated)")
differences.plot(ax=axs[1, 0], cmap="RdBu_r", center=0)
axs[1, 0].set_title("Original - aggregated")
axs[1, 1].scatter(o, d, s=4, alpha=0.5)
lim = [0, max(o.max(), d.max())]
axs[1, 1].plot(lim, lim, "k--", lw=1)
axs[1, 1].set_xlabel("dcSIF original")
axs[1, 1].set_ylabel("SIF downscaled, aggregated")
plt.tight_layout()
```

### Remarks

- The comparison above is a consistency check: the parameters are fitted on the same dcSIF field, so a good agreement shows that the model fits well and that the downscaling does not introduce a bias at the original resolution, but it does not validate the patterns within each 0.05° cell. An independent validation would need higher-resolution references, such as OCO-2/OCO-3 SIF soundings or GPP from eddy-covariance sites.
- SIF values over water bodies (e.g. Lake Balaton) come from mixed footprints in the gridding and should be masked before interpreting the results.
- Within one moving window the range of LST can be narrow, which makes $b_5$ and $b_6$ hard to constrain; parameters at the bounds (printed above) indicate this.
